# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maytinh.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 703)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Screen = QtWidgets.QLabel(self.centralwidget)
        self.Screen.setGeometry(QtCore.QRect(23, 32, 401, 149))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.Screen.setFont(font)
        self.Screen.setFrameShape(QtWidgets.QFrame.Box)
        self.Screen.setLineWidth(2)
        self.Screen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Screen.setObjectName("Screen")
        self.Percent_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Percent_Button.setGeometry(QtCore.QRect(23, 188, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Percent_Button.setFont(font)
        self.Percent_Button.setObjectName("Percent_Button")
        self.Clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Clear_Button.setGeometry(QtCore.QRect(128, 188, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Clear_Button.setFont(font)
        self.Clear_Button.setObjectName("Clear_Button")
        self.Arrow_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Arrow_Button.setGeometry(QtCore.QRect(228, 188, 97, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Arrow_Button.setFont(font)
        self.Arrow_Button.setObjectName("Arrow_Button")
        self.Devide_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Devide_Button.setGeometry(QtCore.QRect(332, 188, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Devide_Button.setFont(font)
        self.Devide_Button.setObjectName("Devide_Button")
        self.Button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_8.setGeometry(QtCore.QRect(128, 276, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_8.setFont(font)
        self.Button_8.setObjectName("Button_8")
        self.Multiply_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Multiply_Button.setGeometry(QtCore.QRect(332, 276, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Multiply_Button.setFont(font)
        self.Multiply_Button.setObjectName("Multiply_Button")
        self.Button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_9.setGeometry(QtCore.QRect(228, 276, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_9.setFont(font)
        self.Button_9.setObjectName("Button_9")
        self.Button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_7.setGeometry(QtCore.QRect(23, 276, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_7.setFont(font)
        self.Button_7.setObjectName("Button_7")
        self.Button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_5.setGeometry(QtCore.QRect(128, 364, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_5.setFont(font)
        self.Button_5.setObjectName("Button_5")
        self.Minus_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Minus_Button.setGeometry(QtCore.QRect(332, 364, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Minus_Button.setFont(font)
        self.Minus_Button.setObjectName("Minus_Button")
        self.Button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_6.setGeometry(QtCore.QRect(228, 364, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_6.setFont(font)
        self.Button_6.setObjectName("Button_6")
        self.Button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_4.setGeometry(QtCore.QRect(23, 364, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_4.setFont(font)
        self.Button_4.setObjectName("Button_4")
        self.Button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_2.setGeometry(QtCore.QRect(128, 452, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_2.setFont(font)
        self.Button_2.setObjectName("Button_2")
        self.Add_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Add_Button.setGeometry(QtCore.QRect(332, 452, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Add_Button.setFont(font)
        self.Add_Button.setObjectName("Add_Button")
        self.Button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_3.setGeometry(QtCore.QRect(228, 452, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_3.setFont(font)
        self.Button_3.setObjectName("Button_3")
        self.Button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_1.setGeometry(QtCore.QRect(23, 452, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_1.setFont(font)
        self.Button_1.setObjectName("Button_1")
        self.Button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_0.setGeometry(QtCore.QRect(128, 540, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Button_0.setFont(font)
        self.Button_0.setObjectName("Button_0")
        self.Equal_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Equal_Button.setGeometry(QtCore.QRect(332, 540, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Equal_Button.setFont(font)
        self.Equal_Button.setObjectName("Equal_Button")
        self.Decimal_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Decimal_Button.setGeometry(QtCore.QRect(228, 540, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Decimal_Button.setFont(font)
        self.Decimal_Button.setObjectName("Decimal_Button")
        self.Plus_Minus_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Plus_Minus_Button.setGeometry(QtCore.QRect(23, 540, 98, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Plus_Minus_Button.setFont(font)
        self.Plus_Minus_Button.setObjectName("Plus_Minus_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Screen.setText(_translate("MainWindow", "0"))
        self.Percent_Button.setText(_translate("MainWindow", "%"))
        self.Clear_Button.setText(_translate("MainWindow", "C"))
        self.Arrow_Button.setText(_translate("MainWindow", "<<"))
        self.Devide_Button.setText(_translate("MainWindow", "/"))
        self.Button_8.setText(_translate("MainWindow", "8"))
        self.Multiply_Button.setText(_translate("MainWindow", "*"))
        self.Button_9.setText(_translate("MainWindow", "9"))
        self.Button_7.setText(_translate("MainWindow", "7"))
        self.Button_5.setText(_translate("MainWindow", "5"))
        self.Minus_Button.setText(_translate("MainWindow", "-"))
        self.Button_6.setText(_translate("MainWindow", "6"))
        self.Button_4.setText(_translate("MainWindow", "4"))
        self.Button_2.setText(_translate("MainWindow", "2"))
        self.Add_Button.setText(_translate("MainWindow", "+"))
        self.Button_3.setText(_translate("MainWindow", "3"))
        self.Button_1.setText(_translate("MainWindow", "1"))
        self.Button_0.setText(_translate("MainWindow", "0"))
        self.Equal_Button.setText(_translate("MainWindow", "="))
        self.Decimal_Button.setText(_translate("MainWindow", "."))
        self.Plus_Minus_Button.setText(_translate("MainWindow", "+/-"))
